// @ts-nocheck

import { Suspense, useMemo } from "react"
import { Navigate, useRoutes } from "react-router-dom"
import routes from "~react-pages"
import { LoadingScreen } from "./components/loading-screen"
import { Toaster } from "sonner"
import ProtectedLayout from "./layouts/ProtectedLayout"
import ItemsPage from "./pages/items"

// import ProtectedLayout from "./layouts/ProtectedLayout" // Import the layout component
// import NotFoundPage from "./pages/not-found"

// Define paths that should NOT use the ProtectedLayout
const PUBLIC_PATHS = ["login", "change-password", "registration"] // Add all exact public paths

// Define paths that should be children of ProtectedLayout
// (You could auto-generate this or list explicitly if simpler)
// For now, we'll assume anything NOT public goes inside ProtectedLayout
// You might need more complex logic for nested public/protected routes

function App() {
  // Restructure the routes generated by vite-plugin-pages
  const restructuredRoutes = useMemo(() => {
    const publicRoutes: typeof routes = []
    const protectedRouteDefinitions: typeof routes = []

    routes.forEach((route) => {
      // Check if the route's path (or its base path for nested routes) is public
      // This simple check assumes top-level routes. Adjust if you have nested public routes.
      if (PUBLIC_PATHS.includes(route.path ?? "")) {
        publicRoutes.push(route)
      } else {
        // Any route not explicitly public will be nested under ProtectedLayout
        protectedRouteDefinitions.push(route)
      }
    })

    protectedRouteDefinitions.push({
      path: "items",
      element: <ItemsPage />,
    })

    // Create the final route configuration
    return [
      {
        path: "/", // Redirect root to /home
        element: <Navigate to="/home" replace />,
      },
      ...publicRoutes, // Add all public routes at the top level
      {
        // Define the parent route using ProtectedLayout as the element
        element: <ProtectedLayout />,
        // Nest all protected route definitions as children
        children: protectedRouteDefinitions,
      },
      // You might add a catch-all 404 route here if vite-plugin-pages doesn't handle it
      { path: "*", element: <div>Not Found</div> },
    ]
  }, []) // Empty dependency array means this runs once

  // useRoutes hook now consumes the RESTRUCTURED routes config
  const element = useRoutes(restructuredRoutes)

  return (
    // Ensure AuthProvider is wrapping this App component somewhere higher up!
    <Suspense fallback={<LoadingScreen />}>
      <Toaster richColors />
      {/* Render the element resolved by useRoutes based on the restructured config */}
      {element}
    </Suspense>
  )
}

export default App
